#[derive(Debug, Eq, Clone, PartialEq)]
pub enum Token {
    Illegal,
    Function,
    Eof,
    Assign,
    Plus,
    Minus,
    Bang,
    Asterisk,
    Slash,
    GreaterThan,
    LessThan,
    Int(String),
    Identifier(String),
    LeftParentesis,
    Let,
    Comma,
    RightParentesis,
    LeftBrace,
    RightBrace,
}
